pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "ubaidullah334/my-app"
        REGISTRY_CREDENTIALS = 'dockerhub-creds' // DockerHub credentials in Jenkins
    }

    parameters {
        choice(name: 'ENV', choices: ['dev', 'qa', 'prod'], description: 'Select environment for deployment')
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the main branch from GitHub using credentials
                git branch: 'main', url: 'https://github.com/ubaid-syed016/my-app-ci-cd.git', credentialsId: 'github-pat'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Change directory to 'app' before installing dependencies
                dir('app') {
                    sh 'npm install'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('app') {
                    sh 'npm test'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('app') {
                    sh 'npm run lint'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def imageTag = "v${env.BUILD_NUMBER}"
                    // Build Docker image from docker/Dockerfile
                    docker.build("${DOCKER_IMAGE}:${imageTag}", "-f docker/Dockerfile .")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${REGISTRY_CREDENTIALS}") {
                        def imageTag = "v${env.BUILD_NUMBER}"
                        docker.image("${DOCKER_IMAGE}:${imageTag}").push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def envFile = "config/${params.ENV}.env"
                    def imageTag = "v${env.BUILD_NUMBER}"

                    // Run container with selected environment
                    sh """
                        docker run -d --rm --name my-app-${params.ENV} --env-file ${envFile} -p \${PORT}:\${PORT} ${DOCKER_IMAGE}:${imageTag}
                    """
                }
            }
        }

        stage('Integration Tests') {
            steps {
                dir('app') {
                    sh 'npm run integration-test'
                }
            }
        }

        stage('Approval for QA/Prod') {
            when { expression { params.ENV != 'dev' } }
            steps {
                input message: "Approve deployment to ${params.ENV}?"
            }
        }
    }

    post {
        success {
            echo "Pipeline successful for ${params.ENV}"
        }
        failure {
            echo "Pipeline failed, performing rollback..."
            sh 'docker container prune -f'
        }
    }
}
